// <auto-generated />
namespace JabuBackendServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingluthkemp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingluthkemp));
        
        string IMigrationMetadata.Id
        {
            get { return "201704281226208_adding luthkemp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
